source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'

# comment this prior to launch to see if any warnings could cause serious errors
inhibit_all_warnings!

use_frameworks!

target 'Habanero' do
  pod 'Habanero', :path => '../'
  pod 'JValidator', '~> 0.1.0' # string validation

  target 'Habanero_Tests' do
    inherit! :search_paths
  end
end
